In [2]:
import os
import json
import psycopg2
from psycopg2.extras import DictCursor
POSTGRESQL_HOST = '10.129.0.25'
%load_ext sql

In [3]:
CONNECT_DATA = 'postgresql://{}:{}@{}/{}'.format(
    os.environ['POSTGRESQL_USER'],
    os.environ['POSTGRESQL_PASSWORD'],
    POSTGRESQL_HOST,
    'demo'
)

1. Which fare conditions are available for flights from AER to SVO (i.e. from Adler/Sochi to Sheremetevo/Moscow

In [4]:
%%sql $CONNECT_DATA
SELECT fare_conditions 
FROM Seats 
WHERE aircraft_code in(
        SELECT aircraft_code
    FROM Flights 
    WHERE departure_airport='AER' AND arrival_airport='SVO')

402 rows affected.

[('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Comfort',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Economy',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',),
 ('Business',)]

In [5]:
%%sql $CONNECT_DATA
SELECT DISTINCT fare_conditions 
FROM Seats 
WHERE aircraft_code in(
        SELECT aircraft_code
        FROM Flights 
        WHERE departure_airport='AER' AND arrival_airport='SVO')

3 rows affected.

[('Business',), ('Comfort',), ('Economy',)]

2 A list of aircraft models which fly to the Yakutsk OR Abakan cities

In [6]:
%%sql $CONNECT_DATA
SELECT model 
FROM aircrafts WHERE aircraft_code in (
        SELECT aircraft_code
         FROM flights WHERE departure_airport in(
             SELECT airport_code FROM airports WHERE
                 city='Yakutsk' or city='Abakan'))

5 rows affected.

[('Airbus A319-100',),
 ('Cessna 208 Caravan',),
 ('Boeing 737-300',),
 ('Bombardier CRJ-200',),
 ('Sukhoi Superjet-100',)]

3. A list of aircraft models which fly to the Yakutsk AND Abakan cities

In [7]:
%%sql $CONNECT_DATA
SELECT model 
FROM aircrafts WHERE aircraft_code in (
        SELECT aircraft_code
         FROM flights WHERE departure_airport in(
             SELECT airport_code FROM airports WHERE
                 city='Yakutsk'))
AND
 aircraft_code in (
        SELECT aircraft_code
         FROM flights WHERE departure_airport in(
             SELECT airport_code FROM airports WHERE
                  city='Abakan'))

1 rows affected.

[('Airbus A319-100',)]

4. A list of aircrafts which DON’T fly to Yakutsk city

In [8]:
%%sql $CONNECT_DATA
SELECT DISTINCT model  
FROM aircrafts 
WHERE aircraft_code NOT IN (  
    SELECT DISTINCT aircraft_code  
    FROM flights  
    WHERE departure_airport NOT IN (
        SELECT airport_code
            FROM 
            airports WHERE city = 'Yakutsk'))

1 rows affected.

[('Airbus A320-200',)]

5. Find out airport codes related to Mrs. 'ELLA DMITRIEVA' - from where and to where she flew.

In [18]:
%%sql $CONNECT_DATA
SELECT DISTINCT departure_airport, arrival_airport
    FROM Flights
      WHERE Flight_id IN(
     SELECT flight_id
        FROM Ticket_flights
       WHERE ticket_no IN(
         SELECT ticket_no
             From Tickets
          WHERE passenger_name= 'ELLA DMITRIEVA'))

7 rows affected.

[('DME', 'HMA'),
 ('DME', 'UUS'),
 ('HMA', 'DME'),
 ('MQF', 'SVX'),
 ('SVO', 'SVX'),
 ('SVX', 'MQF'),
 ('SVX', 'SVO')]

In [19]:
%%sql $CONNECT_DATA  

SELECT DISTINCT departure_airport, arrival_airport  
FROM Flights F  
JOIN Ticket_flights TF USING (flight_id) 
JOIN Tickets T USING(ticket_no)  
WHERE T.passenger_name = 'ELLA DMITRIEVA'

7 rows affected.

[('DME', 'HMA'),
 ('DME', 'UUS'),
 ('HMA', 'DME'),
 ('MQF', 'SVX'),
 ('SVO', 'SVX'),
 ('SVX', 'MQF'),
 ('SVX', 'SVO')]